spring:
  datasource:
    url: jdbc:mysql://localhost:3306/family_db
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf:
    cache: false

security:
  basic:
    enabled: false

#binq.url: http://gateway-test-in-proc.test.hcscint.net/services/ccsp/uat-3a/BenefitInquiry/v4