spring:
  datasource:
    url: jdbc:mysql://localhost:3306/family_db
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
  thymeleaf:
    cache: false

security:
  basic:
    enabled: false
