platform: linux

resources:
- name: resource-family-code
  type: git
  source:
    uri: https://github.com/rwidtmann/family-app.git

jobs:
- name: job-rich-22
  public: true
  plan:
  - get: resource-family-code
  - task: hello-world
    file: resource-family-code/ci/task_hello_world.yml
  - task: step-two
    file: resource-family-code/ci/myRun2.sh