config: &CONFIG
  platform: linux

resources:
- name: resource-code
  type: git
  source:
    uri: https://github.com/rwidtmann/family-app.git


jobs:
- name: job-deploy-development
  public: true
  plan:
  - get: resource-code
  - task: deploy-development
      run:
        dir: resource-code
        path: ./gradlew
        args: cfPush
