config: &CONFIG
  platform: linux

resources:
- name: code
  type: git
  source:
    uri: https://github.com/rwidtmann/family-app.git
    username: rwidtmann@sbcglobal.net
    password: kato1rjw
    branch: master
    skip_ssl_verification: true


jobs:
- name: deploy-development
  plan:
  - get: code
    trigger: true
  - task: deploy-development
    config:
      inputs:
      - name: code
      run:
        dir: code
        path: ./gradlew
        args: cfPush
      params: &cf-development-params
        VERSION: latest-version/number
        CF_TARGET: https://api.run.pivotal.io
        CF_ORGANIZATION: widtmann
        CF_USERNAME: rwidtmann@sbcglobal.net
        CF_PASSWORD: Kato1!rjw
        CF_APPLICATION: family-app
        CF_SPACE: development